services:
    liferay:
        deploy:
            resources:
                limits:
                    memory: 6G
                reservations:
                    memory: 6G
        environment:
            - LIFERAY_COMPANY_PERIOD_SECURITY_PERIOD_STRANGERS_PERIOD_VERIFY=false
            - LIFERAY_JPDA_ENABLED=true
            - LIFERAY_JVM_OPTS=-Djdk.util.zip.disableZip64ExtraFieldValidation=true
            - LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED=false
            - LIFERAY_VIRTUAL_PERIOD_HOSTS_PERIOD_VALID_PERIOD_HOSTS=*
            - LIFERAY_WEB_PERIOD_SERVER_PERIOD_PROTOCOL=http
        hostname: liferay
        image: liferay/dxp:7.4.13-u46
        ports:
            - 8000:8000
            - 8080:8080